# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build and Release

on:
  push:
    tags:
      - 'v*' # 例如 v1.0.0

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        goos: [windows, linux, darwin]
        goarch: [386, arm64]
        exclude:
        - goos: darwin
          goarch: 386

    name: Build for ${{ matrix.goos }}-${{ matrix.goarch }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.22

      - name: Build binary
        run: |
          mkdir -p dist
          export GOOS=${{ matrix.goos }}
          export GOARCH=${{ matrix.goarch }}
          ext=""
          if [ "$GOOS" = "windows" ]; then
            ext=".exe"
          fi
          output="qn-decode-${GOOS}-${GOARCH}${ext}"
          go build -o dist/$output

      - name: Upload Release Assets
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
